import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/src/store/StoreProvider";
import { HeroUIProvider, ToastProvider } from "@heroui/react";
import Providers from "./Provider";
import PageTransition from "@/components/PageTransition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* <PageTransition> */}
          <main className="light text-foreground bg-background">
            {children}
          </main>
          {/* </PageTransition> */}
        </Providers>

      </body>
    </html >
  );
}
